### ISSUE TITLE
Set time picker time with Javascript

### ISSUE THREAD

**Issue by bradt** [winmarkltd/BootstrapFormHelpers#184]
I'd like to set the time picker time using Javascript. From what I can tell from the docs, there's no easy way to do this. You can set the time using an HTML data attribute, but not with a call to a function. Ideally, I'd like to do this:

```
var timepicker = $element.data('bfhtimepicker');
timepicker.setTime('11:30 PM');
```

Is there a way to do this that I'm missing?

**Comment by MaggieRezo** [comment]
If you do that with datepicker the date changes but the pop up with the calendar is pointing to the wrong date.

**Comment by shivamgupta-codebrew** [comment]
AM PM not working 
how to add mode through javascript?
