### ISSUE TITLE
selectbox hidden input does not trigger change event?

### ISSUE THREAD

**Issue by 01iv3r** [winmarkltd/BootstrapFormHelpers#71]
The selectbox helper doesn't seem to trigger a change event when the value is changed on it's hidden input.

see: http://stackoverflow.com/questions/6533087/jquery-detect-value-change-on-hidden-input-field/8965804#8965804

What's the best way is to get a countries selectbox to update the data-country attribute on a bfh-phone input when the hidden input value is changed?

**Comment by oneleft** [comment]
This is still an issue for me and I am using 2.3.0... did it get broken in an update? is there a way I can manually trigger the change event and cause bfh-phone to update?
